### ISSUE TITLE
VUE 3.x and Tailwind 

### ISSUE THREAD

**Issue by pinheiroweb** [newera-systems/parse-vue-datagrid-engine#13]
Congratulations fo the excellent project!

Does it work with VUE 3.x?

Can I use Tailwind CSS?

Thanks

**Comment by josiaskas** [comment]
Hello @pinheiroweb,
Thank you for your kind words and interest in our project!
Currently, our plugin is designed to work with **Vue 2.x**. As of now, it does not support Vue 3.x, you can build some custom component with tailwind, but with Vue 2.x.

However, we understand the growing popularity and demand for Tailwind CSS, and deprecation of Vue 2. We are planning to adapt our plugin for Vue 3 in the future. As part of this adaptation, we are also considering the possibility of integrating Tailwind CSS, especially given the difficulty of  BootstrapVue to support for Vue 3.
> Please note that these are plans for future development and the current version of the plugin is only compatible with Vue 2.

We appreciate your understanding and patience as we work on these improvements. Please stay tuned for updates on our progress.

**Comment by pinheiroweb** [comment]
Thanks a lot !
All the best for you !

Em seg., 10 de jul. de 2023 18:51, Josias kasongo ***@***.***>
escreveu:

**Comment by sadortun** [comment]
Closing for now. We will probably have a look at a solution for Vue3 sometime in the next year.
